### PR TITLE
Fix model import when `graph.value_info` is empty

### PR DESCRIPTION
**Pull request by aclex**
Unfortunately, #310 broke ONNX import for models with graphs which don't have inputs and outputs of the nodes mentioned in `value_info` field of the graph, which is [optional](https://github.com/onnx/onnx/blob/f81558d4b24e910cbd05990f09e4ae78b7452560/onnx/onnx.proto#L463) and not the case e.g. for default export function in recent versions of PyTorch. The problem is that now it tries to obtain shape and data type of the output when converting `Conv` and `ConvTranspose` op nodes, while this information may only be found in graph's `value_info`. When it's there, it's there, otherwise (which is normal as per ONNX spec as well) it may only be inferred during the convertion of the exact same node which tries to search for it. Little recursive thing.

For the `Conv` the fix is pretty straightforward: output shape is simply not used and is removed, while output data type is the same as input data type (and weights data type) again according to the corresponding [ONNX op spec](https://github.com/onnx/onnx/blob/main/docs/Operators.md#type-constraints-26), both in older versions and those ones from 11 onwards. It is used in some new code added in #549, hopefully it respects the specification and nothing is broken with this change.

For the `ConvTranspose` I have to bring back `generate_output_shape()` from #103 helper function to initialize output shape. Still I change it to follow the output shape calculation found in the [`conv2d` IR op constructor](https://github.com/kendryte/nncase/blob/4173d50266f560bca9859dd92b1c176f127b3392/src/ir/ops/conv2d.cpp#L28). Hope it's good enough default value. When `output_shape` attribute is found, output shape is overriden from its value. The rest calculations are preserved.

I'm pretty sure it's fine for simple `Conv`, but could you please double check that it works properly for `ConvTranspose` case? I see there used to be some output shape issues which was going to be solved in #310, hopefully they are remaining fixed :)

### CODE REVIEW

**Comment by zhangyang2057** [comment]
Generally speaking, we strongly recommend the user will use onnx-simplifier to simplify onnx model, all of nodes will have both inputs and outputs information.

**Comment by aclex** [comment]
That's probably a way to go, but the problem is `ncc` refuses to parse valid ONNX passed from vanilla framework with some strange error, while it has all the necessary information to parse it successfully. Not good user experience, in my opinion.

As for the test failing I see in the CI output, I'll try to fix it as soon, as possible.

**Comment by aclex** [comment]
Sorry for delay with the test failure fixes I promised to make, was a little busy this time. I seem to fix the failure putting the output shape generation code into the fallback for `ConvTranspose` op. I also fixed the calculations according to the formula in `ConvTranspose` description in [official ONNX operators guide](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvTranspose). And rebased the branch against `master` to keep it fresh. Hopefully it's now ready for review.

What I wanted to mention is that while fixing the test case I noticed it seems to have a couple of issues:

1. Kernel shape is surprisingly `3×3×3×3` (for `-3-` variants). I think, it shouldn't have `3` in batch and channel axes, as it's quite strange how can this be calculated, given the input shape is e.g. `1×3×16×16`. I assume kernel shape should be `1×1×3×3` in those test cases where it's pixel-wise and `1×3×3×3` where it's depth-wise.
2. Expected output shapes of the test case don't tally too well with the [formula mentioned above](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvTranspose), [visualization](https://github.com/vdumoulin/conv_arithmetic/blob/master/README.md#transposed-convolution-animations) and obviously the [paper](https://www.matthewzeiler.com/mattzeiler/deconvolutionalnetworks.pdf). Here's a table of differences (please, ignore difference in two first axes, it's because of p. 1):

| Parameters | test case | ONNX doc |
|-----------|-------|-------|
| None-pad0-None-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 16 16 | 3 5 18 18 |
| None-pad0-None-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 16 16 | 3 5 18 18 |
| None-pad0-None-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 16 16 | 3 5 18 18 |
| None-pad0-None-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 16 16 | 3 5 18 18 |
| None-pad0-None-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 16 16 | 3 3 18 18 |
| None-pad0-None-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 16 16 | 3 3 18 18 |
| None-pad0-None-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 16 16 | 3 3 18 18 |
| None-pad0-None-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 16 16 | 3 3 18 18 |
| stride1-pad0-None-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 31 46 | 3 5 33 48 |
| stride1-pad0-None-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 31 46 | 3 5 33 48 |
| stride1-pad0-None-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 31 46 | 3 5 33 48 |
| stride1-pad0-None-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 31 46 | 3 5 33 48 |
| stride1-pad0-None-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 31 46 | 3 3 33 48 |
| stride1-pad0-None-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 31 46 | 3 3 33 48 |
| stride1-pad0-None-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 31 46 | 3 3 33 48 |
| stride1-pad0-None-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 31 46 | 3 3 33 48 |
| stride1-pad0-output_padding1-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 32 47 | 3 5 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 32 47 | 3 5 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 32 47 | 3 5 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 32 47 | 3 5 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 32 47 | 3 3 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 32 47 | 3 3 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 32 47 | 3 3 34 49 |
| stride1-pad0-output_padding1-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 32 47 | 3 3 34 49 |
| stride2-pad0-None-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 46 31 | 3 5 48 33 |
| stride2-pad0-None-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 46 31 | 3 5 48 33 |
| stride2-pad0-None-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 46 31 | 3 5 48 33 |
| stride2-pad0-None-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 46 31 | 3 5 48 33 |
| stride2-pad0-None-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 46 31 | 3 3 48 33 |
| stride2-pad0-None-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 46 31 | 3 3 48 33 |
| stride2-pad0-None-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 46 31 | 3 3 48 33 |
| stride2-pad0-None-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 46 31 | 3 3 48 33 |
| stride2-pad0-output_padding1-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 47 32 | 3 5 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 47 32 | 3 5 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 47 32 | 3 5 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 47 32 | 3 5 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 47 32 | 3 3 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 47 32 | 3 3 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 47 32 | 3 3 49 34 |
| stride2-pad0-output_padding1-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 47 32 | 3 3 49 34 |
| stride3-pad0-None-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 46 46 | 3 5 48 48 |
| stride3-pad0-None-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 46 46 | 3 5 48 48 |
| stride3-pad0-None-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 46 46 | 3 5 48 48 |
| stride3-pad0-None-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 46 46 | 3 5 48 48 |
| stride3-pad0-None-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 46 46 | 3 3 48 48 |
| stride3-pad0-None-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 46 46 | 3 3 48 48 |
| stride3-pad0-None-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 46 46 | 3 3 48 48 |
| stride3-pad0-None-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 46 46 | 3 3 48 48 |
| stride3-pad0-output_padding1-kernel_shape0-None-None-None-None-3-in_shape0 | 1 3 47 47 | 3 5 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-None-None-None-bias_shape1-3-in_shape0 | 1 3 47 47 | 3 5 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-None-None-NOTSET-None-3-in_shape0 | 1 3 47 47 | 3 5 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-None-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 47 47 | 3 5 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-3-None-None-None-3-in_shape0 | 1 3 47 47 | 3 3 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-3-None-None-bias_shape1-3-in_shape0 | 1 3 47 47 | 3 3 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-3-None-NOTSET-None-3-in_shape0 | 1 3 47 47 | 3 3 49 49 |
| stride3-pad0-output_padding1-kernel_shape0-3-None-NOTSET-bias_shape1-3-in_shape0 | 1 3 47 47 | 3 3 49 49

This is an example of decomposed calculation according to the formula (for one `None-pad0-None-kernel_shape0-None-None-NOTSET-None-3-in_shape0` case):
```
output_padding: 0 0
input: 1 3 16 16
pads: (0 0 0 0) (0 0 0 0)
kernel: 3 3 3 3
strides: 1 1
dilations: 1 1
output_padding: 0 0
item 0: 0 + 0 + 3 - 0 = 3
item 1: 2 + 0 + 3 - 0 = 5
item 2: 15 + 0 + 3 - 0 = 18
item 3: 15 + 0 + 3 - 0 = 18
output_shape: 3 5 18 18
```
Seems that the only problem is in the `built-in` padding of transposed convolution, which is ignored in the expected values of the test case, but is there when calculated with the formula.

Anyway, again, the test case should pass now, but that's thanks to the output shape specified explicitly (shape generation isn't run).

**Comment by sunnycase** [comment]
Sorry, I think we need to close this pr as it's not valid anymore. Thank you for your contribution.

**Comment by aclex** [comment]
No problem) Yes, I've noticed the package seems to be completely rewritten now. Many thanks for your kind assistance with many of my previous requests!

**Pull request closed without merging**
